package com.seeyoui.kensite.drools.order

import com.seeyoui.kensite.drools.order.Order;

global Integer num;

rule "First Rule"
	when
		order:Order(sumprice>30,sumprice<=50);
	then
		order.setDiscountPercent(98);
end

rule "Second Rule"
	when
		order:Order(sumprice>50,sumprice<=100);
	then
		order.setDiscountPercent(95);
end

rule "third Rule"
	when
		order:Order(sumprice>num);
	then
		order.setDiscountPercent(90);
end